import { NextResponse } from 'next/server';
import { createServiceClient, getAuthenticatedUser } from '@/lib/server';
import { decryptSecret } from '@/lib/crypto';

async function refreshAccessToken(refreshToken:string){const clientId=process.env.YOUTUBE_CLIENT_ID,clientSecret=process.env.YOUTUBE_CLIENT_SECRET;if(!clientId||!clientSecret)throw new Error('YouTube OAuth credentials are not configured.');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:clientId,client_secret:clientSecret,refresh_token:refreshToken,grant_type:'refresh_token'})});const d=await r.json();if(!r.ok)throw new Error(JSON.stringify(d));return d.access_token as string;}

export async function POST(request:Request){
 const user=await getAuthenticatedUser(request);if(!user)return NextResponse.json({error:'Sign in required.'},{status:401});const service=createServiceClient();
 try{const {videoId,title,description,privacyStatus='private'}=await request.json();const {data:video}=await service.from('videos').select('id,video_url').eq('id',videoId).eq('user_id',user.id).maybeSingle();const {data:account}=await service.from('youtube_accounts').select('access_token,refresh_token').eq('user_id',user.id).limit(1).maybeSingle();if(!video?.video_url)return NextResponse.json({error:'Video not found.'},{status:404});if(!account)return NextResponse.json({error:'Connect a YouTube channel first.'},{status:400});let token=account.refresh_token?await refreshAccessToken(decryptSecret(account.refresh_token)):(account.access_token?decryptSecret(account.access_token):null);if(!token)throw new Error('No YouTube token available.');const {data:signed}=await service.storage.from('videos').createSignedUrl(video.video_url,600);if(!signed?.signedUrl)throw new Error('Could not create a signed video URL.');const stored=await fetch(signed.signedUrl);if(!stored.ok)throw new Error(`Stored video download failed (${stored.status}).`);const buffer=await stored.arrayBuffer();const mime=video.video_url.toLowerCase().endsWith('.webm')?'video/webm':'video/mp4';const init=await fetch('https://www.googleapis.com/upload/youtube/v3/videos?uploadType=resumable&part=snippet,status',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json; charset=UTF-8','X-Upload-Content-Length':String(buffer.byteLength),'X-Upload-Content-Type':mime},body:JSON.stringify({snippet:{title:String(title||'Brainrot Studio'),description:String(description||''),categoryId:'24'},status:{privacyStatus:String(privacyStatus)}})});if(!init.ok)throw new Error(await init.text());const uploadUrl=init.headers.get('location');if(!uploadUrl)throw new Error('YouTube did not return an upload URL.');const uploaded=await fetch(uploadUrl,{method:'PUT',headers:{Authorization:`Bearer ${token}`,'Content-Type':mime,'Content-Length':String(buffer.byteLength)},body:buffer});const result=await uploaded.json();if(!uploaded.ok)throw new Error(JSON.stringify(result));await service.from('videos').update({status:'uploaded'}).eq('id',videoId).eq('user_id',user.id);return NextResponse.json({youtubeVideoId:result.id});}
 catch(error){return NextResponse.json({error:error instanceof Error?error.message:'YouTube upload failed.'},{status:500});}
}
